### ISSUE TITLE
Token server environment vars

### ISSUE THREAD

**Issue by rk16449** [commerceblock/mercurylayer#111]
Add token server variables to the environment in dockerfile so that this can work:

```
  token-server:
    build:
      context: token-server
      dockerfile: Dockerfile
    environment:
      - PROCESSOR_URL = "http://0.0.0.0:18080"
      - API_KEY = "aaaaa"
      - FEE = 10000
      - UNIT = "BTC"
      - DELAY = 3600
      - DB_USER = "mercurylayer"
      - DB_PASSWORD = "<CHANGEME>"
      - DB_HOST = "<CHANGEME>"
      - DB_PORT = 5432
      - DB_NAME = "mercury"
```
